[3.x] Feature/change table names issue 79
Qoraiche/laravel-mail-editor pull request #194
Opened 2022-02-09 20:34 UTC by ReeceM

## Description

This PR adds the option to have the subject displayed in the Mailables table. There is also a title hint left which has the value of the classname.

## Related Issue

Closes #79 

## Motivation and Context

UX

## How Has This Been Tested?

Tested, no side effects noticed in rendering.

## Screenshots (if appropriate):

## Types of changes

- [x] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] ~Breaking change (fix or feature that would cause existing functionality to change)~

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [x] I have updated the documentation accordingly.
- [x] I have read the **CONTRIBUTING** document.
- [x] I have added tests to cover my changes.
~- [ ] All new and existing tests passed.~

2022-02-09 20:55 UTC, Qoraiche commented
Thanks for the PR @ReeceM LGTM, just one thing: 
I think would be better if we make the display configured (e.g: display_subject).
also, did you test it with dynamic values?

2022-02-09 21:22 UTC, ReeceM commented
Hi @Qoraiche, glad it looks good.

With the config option are you thinking something like:
```php
if (config('maileclipse.display_subject', false)) {
    /** @see \Illuminate\Mail\Mailable@buildSubject for the Str Functions, used to keep consistent. */
    $fqcns[$i]['subject'] = $mailable_data->subject ?? Str::title(Str::snake(class_basename($mailableClass), ' '));
}
```

I tested using the result from having the `->subject()` method called in the `build` function. Then also the `$subject` prop defined in the Mailable. Are those the ones specifically? :)

2022-02-09 23:14 UTC, Qoraiche requested changes

2022-02-09 23:14 UTC, Qoraiche commented on resources/views/sections/mailables.blade.php
> +                                <th scope="col">{{ __('Subject') }}</th>
Add ability to switch subject/namespace (based on config value)

2022-02-09 23:14 UTC, Qoraiche commented on src/MailEclipse.php
> +                        $fqcns[$i]['subject'] = $mailable_data->subject ?? Str::title(Str::snake(class_basename($mailableClass), ' '));
Switch value based on config, Thanks!!

2022-02-11 00:41 UTC, Qoraiche approved these changes

2022-02-11 15:24 UTC, merged